name: SlimefunOreChunks
version: ${project.version}
author: Zethen
description: A Slimefun Addon that adds the various Dusts to the GEO-Miner. Originally created by TheBusyBiscuit, updated by Zethen for Minecraft 1.17.
website: https://github.com/Zethen/SlimefunOreChunks

main: me.zethen.slimefunorechunks.OreChunks
depend: [Slimefun]

api-version: 1.14